# Generated by Django 5.1.3 on 2024-12-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tales',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
