# Generated by Django 5.1.3 on 2024-12-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0003_alter_tales_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tales',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
