# Generated by Django 5.1.3 on 2024-12-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0004_tales_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tales',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tales/'),
        ),
        migrations.AlterField(
            model_name='tales',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
