# Generated by Django 5.1.3 on 2024-12-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0005_alter_tales_photo_alter_tales_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tales',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
