# Generated by Django 5.1.3 on 2024-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0006_alter_tales_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tales',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
