# Generated by Django 5.1.3 on 2025-02-20 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0009_tales_liked_by_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tales',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='tales',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked', to=settings.AUTH_USER_MODEL),
        ),
    ]
